//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ExploreCaliDbF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public int Length { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> RatingId { get; set; }
        public bool IncludesMeals { get; set; }
    
        public virtual Rating Rating { get; set; }
    }
}
